codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: unit
      paths:
        - src/
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: integration
      paths:
        - src/
      statuses:
        - type: project
          target: auto
          threshold: 1%